### ISSUE TITLE
CommonMark support

### ISSUE THREAD

**Issue by TheRadialActive** [meitar/diasposter#3]
Lately I tried to share an article with a table in it. The diaspora\* post looked pretty bad. [Diaspora now supports tables](https://pod.geraspora.de/posts/3732000), but the plugin doesn't. Maybe someone could integrate the commonmark syntax in diasposter

**Comment by fabacab** [comment]
I don't understand German but if Diaspora supports HTML tables natively, then maybe we don't need to translate the WordPress HTML to Markdown syntax at all?

Anyway, thanks for reporting this, I'll look into that as a possibility.

**Comment by fabacab** [comment]
Oh, okay, so it seems Diaspora _doesn't_ allow you to insert most HTML elements into posts directly; Markdown is required for most advanced "HTML" displays (like tables). Unfortunately, WordPress saves content as HTML, so there needs to be an intermediate translation step from WordPress's HTML to Markdown before it gets sent to a Diaspora pod. At the moment, this step is handled by [the HTML_To_Markdown library](https://github.com/nickcernis/html-to-markdown), which still has some [bugs around these parts](https://github.com/nickcernis/html-to-markdown/issues/13). Which is to say, yes, this would be nice, but **patches to improve CommonMark support should be upstreamed to Nick Cernis's library.** :)

**Comment by colinodell** [comment]
> patches to improve CommonMark support should be upstreamed to Nick Cernis's library. :)

As the new maintainer of that project, I'd greatly appreciate any fixes or improvements you might have :)

**Comment by fabacab** [comment]
> As the new maintainer of that project, I'd greatly appreciate any fixes or improvements you might have :)

:+1: :)
